version: "3.9"

services:

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: renttool_db
    environment:
      POSTGRES_DB: renttool
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: anton12
    ports:
      - "5432:5432"